export const timelineStart = "2010-01";
export const timelineEnd = "2026-10";

// `end` is an exclusive month boundary used to size bars. Display labels preserve
// the published transition month (or year when no reliable month is public).
// Latest news review and source notes: docs/data-audit-2026-09-10.md.
export const people = [
  {
    name: "Sam Altman",
    cohort: "openai-founding-team",
    roles: [{ company: "OpenAI", start: "2015-12", end: timelineEnd }],
  },
  {
    name: "Elon Musk",
    cohort: "openai-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2015-12",
        end: "2018-03",
        endLabel: "Feb 2018",
        lane: 0,
      },
      {
        company: "Tesla",
        start: timelineStart,
        startLabel: "Oct 2008",
        end: timelineEnd,
        lane: 1,
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2026-02",
        endLabel: "Feb 2026",
        lane: 2,
      },
      {
        company: "SpaceX",
        start: "2026-02",
        end: timelineEnd,
        lane: 2,
      },
    ],
  },
  {
    name: "Greg Brockman",
    cohort: "openai-founding-team",
    roles: [{ company: "OpenAI", start: "2015-12", end: timelineEnd }],
  },
  {
    name: "Ilya Sutskever",
    cohort: "openai-founding-team",
    roles: [
      {
        company: "DNNresearch",
        start: "2012-11",
        end: "2013-03",
        endLabel: "Mar 2013",
      },
      {
        company: "Google Brain",
        start: "2013-03",
        end: "2015-12",
        endLabel: "Nov 2015",
      },
      {
        company: "OpenAI",
        start: "2015-12",
        end: "2024-06",
        endLabel: "May 2024",
      },
      {
        company: "SSI",
        start: "2024-06",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Andrej Karpathy",
    cohort: "openai-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2015-12",
        end: "2017-07",
        endLabel: "Jun 2017",
        lane: 0,
      },
      {
        company: "Tesla",
        start: "2017-07",
        startLabel: "Jun 2017",
        end: "2022-08",
        endLabel: "Jul 2022",
        lane: 0,
      },
      {
        company: "OpenAI",
        start: "2023-02",
        end: "2024-03",
        endLabel: "Feb 2024",
        lane: 0,
      },
      {
        company: "Eureka Labs",
        start: "2024-07",
        end: "2026-05",
        endLabel: "May 2026",
        lane: 0,
      },
      {
        company: "Anthropic",
        label: "Anth",
        start: "2026-05",
        end: timelineEnd,
        lane: 0,
      },
    ],
  },
  {
    name: "Durk Kingma",
    cohort: "openai-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2015-12",
        end: "2018-07",
        endLabel: "2018",
        lane: 0,
      },
      {
        company: "Google Brain",
        start: "2018-07",
        end: "2023-04",
        lane: 0,
      },
      {
        company: "Google DeepMind",
        start: "2023-04",
        end: "2024-10",
        endLabel: "Oct 2024",
        lane: 0,
      },
      {
        company: "Anthropic",
        start: "2024-10",
        end: timelineEnd,
        lane: 0,
      },
    ],
  },
  {
    name: "John Schulman",
    cohort: "openai-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2015-12",
        end: "2024-08",
        endLabel: "Aug 2024",
        lane: 0,
      },
      {
        company: "Anthropic",
        label: "Anth",
        start: "2024-08",
        end: "2025-02",
        endLabel: "Feb 2025",
        lane: 0,
      },
      {
        company: "Thinking Machines Lab",
        start: "2025-02",
        end: timelineEnd,
        lane: 0,
      },
    ],
  },
  {
    name: "Wojciech Zaremba",
    cohort: "openai-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2015-12",
        end: timelineEnd,
        lane: 0,
      },
    ],
  },
  {
    name: "Yann LeCun",
    cohort: "meta-fair-founding-team",
    roles: [
      {
        company: "NYU CILVR",
        label: "NYU · faculty",
        position: "Faculty",
        start: timelineStart,
        startLabel: "2003",
        end: timelineEnd,
        lane: 1,
      },
      {
        company: "Meta FAIR",
        label: "FAIR",
        start: "2013-12",
        end: "2026-01",
        endLabel: "Dec 2025",
        lane: 0,
      },
      {
        company: "AMI Labs",
        start: "2026-01",
        end: timelineEnd,
        lane: 0,
      },
    ],
  },
  {
    name: "Rob Fergus",
    cohort: "meta-fair-founding-team",
    roles: [
      {
        company: "NYU CILVR",
        label: "NYU · faculty",
        position: "Faculty",
        start: timelineStart,
        startLabel: "2007",
        end: timelineEnd,
        lane: 1,
      },
      {
        company: "Meta FAIR",
        label: "FAIR",
        start: "2013-12",
        end: "2020-06",
        endLabel: "Jun 2020",
        lane: 0,
      },
      {
        company: "DeepMind",
        label: "DM",
        start: "2020-06",
        end: "2023-04",
        lane: 0,
      },
      {
        company: "Google DeepMind",
        label: "GDM",
        start: "2023-04",
        end: "2025-05",
        endLabel: "May 2025",
        lane: 0,
      },
      {
        company: "Meta FAIR",
        label: "FAIR",
        start: "2025-05",
        end: timelineEnd,
        lane: 0,
      },
    ],
  },
  {
    name: "Ashish Vaswani",
    cohort: "transformer-research-team",
    roles: [
      {
        company: "Google Brain",
        start: "2016-07",
        end: "2021-11",
        endLabel: "Oct 2021",
      },
      {
        company: "Adept",
        start: "2021-11",
        end: "2022-11",
        endLabel: "Nov 2022",
      },
      {
        company: "Essential AI",
        start: "2023-01",
        end: "2026-06",
        endLabel: "Jun 2026",
      },
      { company: "NVIDIA", start: "2026-06", end: timelineEnd },
    ],
  },
  {
    name: "Noam Shazeer",
    cohort: "transformer-research-team",
    roles: [
      {
        company: "Google Research",
        start: timelineStart,
        startLabel: "2000",
        end: "2012-01",
        endLabel: "2012",
      },
      {
        company: "Google Brain",
        start: "2012-01",
        startLabel: "2012",
        end: "2021-11",
        endLabel: "Oct 2021",
      },
      {
        company: "Character.AI",
        start: "2021-11",
        end: "2024-08",
        endLabel: "Aug 2024",
      },
      {
        company: "Google DeepMind",
        start: "2024-08",
        end: "2026-06",
        endLabel: "Jun 2026",
      },
      {
        company: "OpenAI",
        label: "OAI",
        start: "2026-06",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Niki Parmar",
    cohort: "transformer-research-team",
    roles: [
      {
        company: "Google Brain",
        start: "2015-06",
        end: "2021-11",
        endLabel: "Nov 2021",
      },
      {
        company: "Adept",
        start: "2021-11",
        end: "2022-11",
        endLabel: "Nov 2022",
      },
      {
        company: "Essential AI",
        start: "2023-01",
        end: "2024-10",
        endLabel: "Sep 2024",
      },
      { company: "Anthropic", start: "2024-12", end: timelineEnd },
    ],
  },
  {
    name: "Jakob Uszkoreit",
    cohort: "transformer-research-team",
    roles: [
      {
        company: "Google Research",
        start: timelineStart,
        startLabel: "2008",
        end: "2012-01",
        endLabel: "2012",
      },
      {
        company: "Google Brain",
        start: "2012-01",
        startLabel: "2012",
        end: "2021-01",
        endLabel: "2021",
      },
      {
        company: "Inceptive",
        start: "2021-01",
        startLabel: "2021",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Llion Jones",
    cohort: "transformer-research-team",
    roles: [
      {
        company: "Google Brain",
        start: "2015-06",
        end: "2023-04",
      },
      {
        company: "Google DeepMind",
        label: "GDM",
        start: "2023-04",
        end: "2023-08",
        endLabel: "Aug 2023",
      },
      { company: "Sakana AI", start: "2023-08", end: timelineEnd },
    ],
  },
  {
    name: "Aidan Gomez",
    cohort: "transformer-research-team",
    roles: [
      {
        company: "Google Brain",
        label: "GB",
        start: "2017-06",
        end: "2017-09",
        endLabel: "2017",
      },
      { company: "Cohere", start: "2019-01", end: timelineEnd },
    ],
  },
  {
    name: "Łukasz Kaiser",
    cohort: "transformer-research-team",
    roles: [
      {
        company: "Google Brain",
        start: "2013-10",
        end: "2021-04",
        endLabel: "2021",
      },
      { company: "OpenAI", start: "2021-04", end: timelineEnd },
    ],
  },
  {
    name: "Illia Polosukhin",
    cohort: "transformer-research-team",
    roles: [
      {
        company: "Google Research",
        start: "2014-01",
        end: "2017-09",
        endLabel: "2017",
      },
      { company: "NEAR", start: "2017-09", end: timelineEnd },
    ],
  },
  {
    name: "Demis Hassabis",
    cohort: "deepmind-founding-team",
    roles: [
      {
        company: "DeepMind",
        start: "2010-09",
        end: "2023-04",
      },
      {
        company: "Google DeepMind",
        position: "CEO",
        start: "2023-04",
        end: "2026-08",
        endLabel: "Aug 2026",
      },
      {
        company: "Google DeepMind",
        label: "Chair",
        position: "Chair",
        start: "2026-08",
        end: timelineEnd,
      },
      {
        company: "Alphabet",
        position: "Chief Scientist",
        start: "2026-08",
        end: timelineEnd,
        lane: 1,
      },
    ],
  },
  {
    name: "Shane Legg",
    cohort: "deepmind-founding-team",
    roles: [
      {
        company: "DeepMind",
        start: "2010-09",
        end: "2023-04",
      },
      { company: "Google DeepMind", start: "2023-04", end: timelineEnd },
    ],
  },
  {
    name: "Mustafa Suleyman",
    cohort: "deepmind-founding-team",
    roles: [
      {
        company: "DeepMind",
        start: "2010-09",
        end: "2019-12",
        endLabel: "Dec 2019",
      },
      {
        company: "Google",
        start: "2019-12",
        end: "2022-01",
        endLabel: "Jan 2022",
      },
      {
        company: "Inflection AI",
        start: "2022-03",
        end: "2024-03",
        endLabel: "Mar 2024",
      },
      { company: "Microsoft AI", start: "2024-03", end: timelineEnd },
    ],
  },
  {
    name: "Dario Amodei",
    cohort: "anthropic-founding-team",
    roles: [
      {
        company: "Baidu AI Lab",
        start: "2014-11",
        end: "2015-11",
        endLabel: "Oct 2015",
      },
      {
        company: "Google Brain",
        start: "2015-11",
        startLabel: "Nov 2015",
        end: "2016-08",
        endLabel: "Aug 2016",
      },
      {
        company: "OpenAI",
        start: "2016-08",
        end: "2021-01",
        endLabel: "Dec 2020",
      },
      { company: "Anthropic", start: "2021-01", end: timelineEnd },
    ],
  },
  {
    name: "Daniela Amodei",
    cohort: "anthropic-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2018-10",
        end: "2021-01",
        endLabel: "Dec 2020",
      },
      { company: "Anthropic", start: "2021-01", end: timelineEnd },
    ],
  },
  {
    name: "Jack Clark",
    cohort: "anthropic-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2016-09",
        end: "2021-01",
        endLabel: "Dec 2020",
      },
      { company: "Anthropic", start: "2021-01", end: timelineEnd },
    ],
  },
  {
    name: "Jared Kaplan",
    cohort: "anthropic-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2019-01",
        end: "2021-01",
        endLabel: "Dec 2020",
      },
      { company: "Anthropic", start: "2021-01", end: timelineEnd },
    ],
  },
  {
    name: "Sam McCandlish",
    cohort: "anthropic-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2018-05",
        end: "2021-01",
        endLabel: "Dec 2020",
      },
      { company: "Anthropic", start: "2021-01", end: timelineEnd },
    ],
  },
  {
    name: "Tom Brown",
    cohort: "anthropic-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2016-05",
        end: "2017-06",
        endLabel: "May 2017",
      },
      {
        company: "Google Brain",
        start: "2017-08",
        end: "2018-12",
        endLabel: "Nov 2018",
      },
      {
        company: "OpenAI",
        start: "2018-12",
        end: "2021-01",
        endLabel: "Dec 2020",
      },
      { company: "Anthropic", start: "2021-01", end: timelineEnd },
    ],
  },
  {
    name: "Chris Olah",
    cohort: "anthropic-founding-team",
    roles: [
      {
        company: "Google Brain",
        start: "2016-01",
        startLabel: "2016",
        end: "2018-10",
        endLabel: "Sep 2018",
      },
      {
        company: "OpenAI",
        start: "2018-10",
        end: "2021-01",
        endLabel: "Dec 2020",
      },
      { company: "Anthropic", start: "2021-01", end: timelineEnd },
    ],
  },
  {
    name: "Ben Mann",
    cohort: "anthropic-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2018-01",
        end: "2021-01",
        endLabel: "Dec 2020",
      },
      { company: "Anthropic", start: "2021-01", end: timelineEnd },
    ],
  },
  {
    name: "Mira Murati",
    cohort: "thinking-machines-founding-team",
    roles: [
      {
        company: "Leap Motion",
        start: "2016-01",
        startLabel: "2016",
        end: "2018-06",
        endLabel: "2018",
      },
      {
        company: "OpenAI",
        start: "2018-06",
        end: "2024-10",
        endLabel: "Sep 2024",
      },
      {
        company: "Thinking Machines Lab",
        start: "2025-02",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Barret Zoph",
    cohort: "thinking-machines-founding-team",
    roles: [
      {
        company: "Google Brain",
        start: "2016-01",
        startLabel: "2016",
        end: "2022-09",
        endLabel: "Aug 2022",
      },
      {
        company: "OpenAI",
        start: "2022-09",
        end: "2024-10",
        endLabel: "Sep 2024",
      },
      {
        company: "Thinking Machines Lab",
        label: "TML",
        start: "2025-02",
        end: "2026-01",
        endLabel: "Jan 2026",
      },
      {
        company: "OpenAI",
        label: "OAI",
        start: "2026-01",
        end: "2026-08",
        endLabel: "Aug 2026",
      },
      {
        company: "Google DeepMind",
        label: "GDM",
        start: "2026-08",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Luke Metz",
    cohort: "thinking-machines-founding-team",
    roles: [
      {
        company: "Google Brain",
        start: "2017-06",
        end: "2022-09",
        endLabel: "Aug 2022",
      },
      {
        company: "OpenAI",
        start: "2022-09",
        end: "2024-10",
        endLabel: "Oct 2024",
      },
      {
        company: "Thinking Machines Lab",
        label: "TML",
        start: "2025-02",
        end: "2026-01",
        endLabel: "Jan 2026",
      },
      {
        company: "OpenAI",
        label: "OAI",
        start: "2026-01",
        end: "2026-08",
        endLabel: "Aug 2026",
      },
      {
        company: "Meta Superintelligence Labs",
        label: "MSL",
        start: "2026-08",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Lilian Weng",
    cohort: "thinking-machines-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2018-01",
        startLabel: "2018",
        end: "2024-12",
        endLabel: "Nov 2024",
      },
      {
        company: "Thinking Machines Lab",
        label: "TML",
        start: "2025-02",
        end: "2026-07",
        endLabel: "Jul 2026",
      },
      {
        company: "OpenAI",
        label: "OAI",
        start: "2026-07",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Andrew Tulloch",
    cohort: "thinking-machines-founding-team",
    roles: [
      {
        company: "Meta FAIR",
        start: "2012-01",
        startLabel: "2012",
        end: "2023-10",
        endLabel: "2023",
      },
      {
        company: "OpenAI",
        label: "OAI",
        start: "2023-10",
        end: "2025-01",
        endLabel: "2024",
      },
      {
        company: "Thinking Machines Lab",
        label: "TML",
        start: "2025-01",
        end: "2025-10",
        endLabel: "Oct 2025",
      },
      {
        company: "Meta Superintelligence Labs",
        label: "MSL",
        start: "2025-10",
        end: "2026-09",
        endLabel: "Sep 2026",
      },
      {
        company: "Anthropic",
        label: "Anth",
        start: "2026-09",
        startLabel: "Sep 2026 (reported)",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Alexandr Wang",
    cohort: "meta-superintelligence-leadership-team",
    roles: [
      {
        company: "Scale AI",
        start: "2016-06",
        startLabel: "2016",
        end: "2025-06",
        endLabel: "Jun 2025",
      },
      {
        company: "Meta Superintelligence Labs",
        start: "2025-06",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Shengjia Zhao",
    cohort: "meta-superintelligence-leadership-team",
    roles: [
      {
        company: "OpenAI",
        start: "2017-01",
        startLabel: "2017",
        end: "2025-06",
        endLabel: "Jun 2025",
      },
      {
        company: "Meta Superintelligence Labs",
        start: "2025-06",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Arthur Mensch",
    cohort: "mistral-founding-team",
    roles: [
      {
        company: "Google DeepMind",
        start: "2020-01",
        startLabel: "2020",
        end: "2023-04",
        endLabel: "Apr 2023",
      },
      { company: "Mistral", start: "2023-04", end: timelineEnd },
    ],
  },
  {
    name: "Guillaume Lample",
    cohort: "mistral-founding-team",
    roles: [
      {
        company: "Meta FAIR",
        start: "2016-01",
        startLabel: "2016",
        end: "2023-04",
        endLabel: "Apr 2023",
      },
      { company: "Mistral", start: "2023-04", end: timelineEnd },
    ],
  },
  {
    name: "Timothée Lacroix",
    cohort: "mistral-founding-team",
    roles: [
      {
        company: "Meta FAIR",
        start: "2017-01",
        startLabel: "2017",
        end: "2023-04",
        endLabel: "Apr 2023",
      },
      { company: "Mistral", start: "2023-04", end: timelineEnd },
    ],
  },
  {
    name: "Daniel Gross",
    cohort: "ssi-founding-team",
    roles: [
      {
        company: "Cue",
        start: timelineStart,
        startLabel: "2010",
        end: "2013-10",
        endLabel: "Oct 2013",
      },
      {
        company: "Apple AI",
        start: "2013-10",
        end: "2017-01",
        endLabel: "Jan 2017",
      },
      {
        company: "SSI",
        start: "2024-06",
        end: "2025-07",
        endLabel: "Jun 2025",
      },
      {
        company: "Meta Superintelligence Labs",
        label: "MSL",
        start: "2025-07",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Daniel Levy",
    cohort: "ssi-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2022-03",
        end: "2024-06",
        endLabel: "Jun 2024",
      },
      { company: "SSI", start: "2024-06", end: timelineEnd },
    ],
  },
  {
    name: "Igor Babuschkin",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "DeepMind",
        start: "2017-01",
        startLabel: "2017",
        end: "2020-11",
        endLabel: "Nov 2020",
      },
      {
        company: "OpenAI",
        start: "2020-11",
        end: "2022-04",
        endLabel: "Mar 2022",
      },
      {
        company: "DeepMind",
        label: "DM",
        start: "2022-04",
        end: "2023-03",
        endLabel: "Feb 2023",
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2025-09",
        endLabel: "Aug 2025",
      },
      {
        company: "River AI",
        start: "2026-04",
        startLabel: "Apr 2026",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Manuel Kroiss",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "DeepMind",
        start: "2019-01",
        startLabel: "by 2019",
        end: "2023-03",
        endLabel: "Feb 2023",
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2026-04",
        endLabel: "Mar 2026",
      },
    ],
  },
  {
    name: "Yuhuai (Tony) Wu",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "Google Research",
        label: "Google",
        start: "2019-01",
        startLabel: "2019",
        end: "2023-03",
        endLabel: "Feb 2023",
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2026-03",
        endLabel: "Feb 2026",
      },
    ],
  },
  {
    name: "Christian Szegedy",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "Google Research",
        label: "Google",
        start: timelineStart,
        startLabel: "2010",
        end: "2023-03",
        endLabel: "Feb 2023",
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2025-03",
        endLabel: "Feb 2025",
      },
      {
        company: "Morph Labs",
        label: "Morph",
        start: "2025-06",
        end: "2025-09",
        endLabel: "Aug 2025",
      },
      {
        company: "Math Inc",
        start: "2025-09",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Jimmy Ba",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "U of T ML",
        label: "U of T · faculty",
        position: "Faculty",
        start: "2018-07",
        startLabel: "2018",
        end: timelineEnd,
        lane: 1,
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2026-03",
        endLabel: "Feb 2026",
        lane: 0,
      },
    ],
  },
  {
    name: "Toby Pohlen",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "DeepMind",
        start: "2017-01",
        startLabel: "2017",
        end: "2023-04",
        endLabel: "Apr 2023",
      },
      {
        company: "Google DeepMind",
        label: "GDM",
        start: "2023-04",
        end: "2023-06",
        endLabel: "Jun 2023",
      },
      {
        company: "xAI",
        start: "2023-06",
        end: "2026-03",
        endLabel: "Feb 2026",
      },
    ],
  },
  {
    name: "Ross Nordeen",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "Tesla",
        start: "2019-07",
        startLabel: "2019",
        end: "2023-03",
        endLabel: "Feb 2023",
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2026-04",
        endLabel: "Mar 2026",
      },
    ],
  },
  {
    name: "Kyle Kosic",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "OpenAI",
        start: "2021-01",
        startLabel: "2021",
        end: "2023-05",
        endLabel: "Apr 2023",
      },
      {
        company: "xAI",
        start: "2023-05",
        end: "2024-07",
        endLabel: "Jun 2024",
      },
      {
        company: "OpenAI",
        start: "2024-07",
        end: "2025-12",
        endLabel: "Nov 2025",
      },
      {
        company: "Project Prometheus",
        label: "Prometheus",
        start: "2026-04",
        startLabel: "by Apr 2026",
        end: "2026-08",
        endLabel: "by Aug 2026",
      },
      {
        company: "River AI",
        label: "River",
        start: "2026-08",
        startLabel: "by Aug 2026",
        end: timelineEnd,
      },
    ],
  },
  {
    name: "Greg Yang",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "Microsoft Research",
        label: "MSR",
        start: "2018-01",
        startLabel: "2018",
        end: "2023-03",
        endLabel: "Feb 2023",
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2026-02",
        endLabel: "Jan 2026",
      },
    ],
  },
  {
    name: "Guodong Zhang",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "DeepMind",
        start: "2022-08",
        end: "2023-03",
        endLabel: "Feb 2023",
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2026-04",
        endLabel: "Mar 2026",
      },
    ],
  },
  {
    name: "Zihang Dai",
    cohort: "xai-founding-team",
    roles: [
      {
        company: "Google Brain",
        start: "2020-06",
        startLabel: "2020",
        end: "2023-03",
        endLabel: "Feb 2023",
      },
      {
        company: "xAI",
        start: "2023-03",
        end: "2026-04",
        endLabel: "Mar 2026",
      },
    ],
  },
];

export const companyColors = {
  Adept: "#806de0",
  Alphabet: "#4f8df0",
  "AMI Labs": "#b65d84",
  Anthropic: "#c86742",
  "Apple AI": "#777c84",
  "Baidu AI Lab": "#3976c5",
  "Character.AI": "#5f9064",
  Cohere: "#5067c6",
  Cue: "#8b6b45",
  DeepMind: "#4788e8",
  DNNresearch: "#6d7784",
  "Eureka Labs": "#bd7a16",
  "Essential AI": "#319181",
  Google: "#4f8df0",
  "Google Brain": "#4f8df0",
  "Google DeepMind": "#4788e8",
  "Google Research": "#4f8df0",
  Inceptive: "#b75382",
  "Inflection AI": "#8773c4",
  "Leap Motion": "#2d9587",
  "Meta FAIR": "#2876d2",
  "Meta Superintelligence Labs": "#316fd1",
  "Microsoft AI": "#4290c3",
  "Microsoft Research": "#4290c3",
  Mistral: "#d46b3e",
  "Math Inc": "#a16440",
  "Morph Labs": "#5977b9",
  NEAR: "#24a08e",
  NVIDIA: "#69a441",
  "NYU CILVR": "#7555a5",
  OpenAI: "#454d50",
  "Project Prometheus": "#b45349",
  "River AI": "#2f8e84",
  "Sakana AI": "#2c7cba",
  "Scale AI": "#397f89",
  SpaceX: "#3d6c93",
  SSI: "#8665cb",
  Tesla: "#db3942",
  "Thinking Machines Lab": "#c44d70",
  "U of T ML": "#397bbb",
  xAI: "#5f686e",
};
